// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwagrefmrmhfjjknmfmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3YWdyZWZtcm1oZmpqa25tZm1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5MTI3MDQsImV4cCI6MjA1NjQ4ODcwNH0.bbQc5T4TUvT-RHCHMdwhUA06VcIRFQXBDMqJAlKutYM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);